### ISSUE TITLE
CI publish step fails on new releases

### ISSUE THREAD

**Issue by djperrefort** [pitt-crc/Slurm-Test-Environment#34]
I created (and then subsequently deleted) a GitHub release to test out the CI. The last step of the publication failed due to an incorrect tag value on the docker image. In the following step:

```yaml
- name: Publish fetched image
  run: |
    docker load --input image.tar
    docker push ghcr.io/${{ github.repository_owner }}/${{ steps.image-name.outputs.name }}:${{ github.ref_name }}
```

The usage of ``:${{ github.ref_name }}`` is incorrect. This will always point to the branch name but sometimes we need to use the release value.

The correct way to do this is to use the output of an earlier CI step that extracts the image metadata:

```yaml
- name: Extract Docker metadata
  id: meta
  uses: docker/metadata-action@v4
  with:
    images: ghcr.io/${{ github.repository_owner }}/${{ steps.image-name.outputs.name }}
```
